### ISSUE TITLE
Segfault on Debian Stretch

### ISSUE THREAD

**Issue by leenooks** [pcloudcom/console-client#119]
Hi, I'm using rsync to backup files to my crypto folder.

While the first run of the rsync seemed to go well (although missed some files strangely) - it ran for many, many days until it finished. (Something like 80,000 files, totalling ~400GB).

Now, when I re-run rsync to pick up files that it missed, after a while pcloudcc core dumps:

```
Thread 25 "pcloudcc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe269c700 (LWP 16819)]
0x00007ffff78fe60b in psync_crypto_sign_auth_sector () from /usr/lib/libpcloudcc_lib.so
(gdb) bt
#0  0x00007ffff78fe60b in psync_crypto_sign_auth_sector () from /usr/lib/libpcloudcc_lib.so
#1  0x00007ffff7923747 in psync_pagecache_read_unmodified_encrypted_locked () from /usr/lib/libpcloudcc_lib.so
#2  0x00007ffff7913155 in ?? () from /usr/lib/libpcloudcc_lib.so
#3  0x00007ffff7659e12 in fuse_fs_read_buf () from /lib/x86_64-linux-gnu/libfuse.so.2
#4  0x00007ffff7659fd2 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007ffff7662a3e in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007ffff76635a1 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#7  0x00007ffff765fd48 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#8  0x00007ffff74374a4 in start_thread (arg=0x7fffe269c700) at pthread_create.c:456
#9  0x00007ffff64bed0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

Pcloud is started with `-u user -m /mnt/pcloud -c` and rsync is doing `rsync -xrltvP /source /mnt/pcloud/Crypto\ Folder`.

Appreciate any advice.

**Comment by livingdeadfr** [comment]
+1
